### ISSUE TITLE
svc_enc_fuzzer: Update to test 420 semi-planar formats

### ISSUE THREAD

**Issue by harishdm** [ittiam-systems/libavc#7]
[svc_enc_fuzzer.cpp#L41](https://github.com/ittiam-systems/libavc/blob/d6441bc469f7fd60855c3bf197625a639e1da65f/fuzzer/svc_enc_fuzzer.cpp#L41) lists only IV_YUV_420P as supported color format, but the library seems to support 420 semi-planar format as well.
Need to update the fuzzer to test for supported semi-planar formats.
If semi-planar is not supported, then fuzzer needs to be updated to remove semi-planar related code and library needs to have a check to reject other formats.

**Comment by AshwinNatesan-ittiam** [comment]
Semi-planar is supported. But, it has not been tested, at all. I will add it to the fuzzer, run it for a week, and raise a PR after.
